AWSTemplateFormatVersion: '2010-09-09'
Description: Compliant CMK S3 assets (demo PASS)
Resources:
  AssetsKey:
    Type: AWS::KMS::Key
    Properties:
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: {AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'}
            Action: 'kms:*'
            Resource: '*'
      Tags:
        - {Key: Owner, Value: platform}
        - {Key: CostCenter, Value: FE-DEMO}
        - {Key: Environment, Value: dev}
  AssetsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !GetAtt AssetsKey.Arn
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - {Key: Owner, Value: platform}
        - {Key: CostCenter, Value: FE-DEMO}
        - {Key: Environment, Value: dev}
